name: gh-page

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - run: make install
      - run: make build
      - run: rm -rf docs || exit 0
      - run: mkdir docs
      - run: cp -r ./dist/build/* docs
      - run: cp  docs/index.html docs/404.html
      - name: push docs
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'update docs'
          force-add: 'true'
          files: docs/*
          name:  gh-actions
          rebase: 'true'
